### ISSUE TITLE
How to add a method on complete event of RotateBehavior

### ISSUE THREAD

**Issue by satya4satyanm** [hyperandroid/CAAT#171]
Hi Please help

var rotateBehaviour = new CAAT.RotateBehavior().setAngles(0, rotationNum).setDelayTime( 0, 12000);
wheel.addBehavior(rotateBehaviour);

I need to call a method on completion of this behavior everytime

Thank you in advance
Satya

**Comment by robboerman** [comment]
You can set a behaviorExpired method on your new behavior to do this. 

    var rotateBehaviour = new CAAT.RotateBehavior().setAngles(0, rotationNum).setDelayTime( 0, 12000);
    rotateBehaviour.behaviorExpired = function(behavior, time, actor) {
        // Do your magic
    }

**Comment by satya4satyanm** [comment]
Thanks Rob
